# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Bopsoft.Listary
PackageVersion: 6.3.2.88
PackageLocale: en-US
Publisher: Bopsoft
PublisherUrl: https://www.listary.com/
PublisherSupportUrl: https://help.listary.com/
PrivacyUrl: https://help.listary.com/privacy
PackageName: Listary
PackageUrl: https://www.listary.com/
License: Proprietary
LicenseUrl: https://help.listary.com/license-agreement
Copyright: © 2010-2024 Bopsoft. All right reserved.
ShortDescription: The revolutionary file search tool for Windows.
Description: Listary is a revolutionary search utility for Windows that makes finding your files and launching apps blazing fast, for casual and power users alike.
Moniker: listary
Tags:
- add-on
- addon
- app
- application
- extension
- find
- launcher
- plugin
- productivity
- search
- tool
- utility
PurchaseUrl: https://www.listary.com/pro
ManifestType: defaultLocale
ManifestVersion: 1.9.0

